# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cities.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cities(object):
    def setupUi(self, cities):
        cities.setObjectName("cities")
        cities.resize(548, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(cities)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 10, 160, 295))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.agianapa = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.agianapa.setObjectName("agianapa")
        self.verticalLayout.addWidget(self.agianapa)
        self.budapesht = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.budapesht.setObjectName("budapesht")
        self.verticalLayout.addWidget(self.budapesht)
        self.salszburg = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.salszburg.setObjectName("salszburg")
        self.verticalLayout.addWidget(self.salszburg)
        self.larnaca = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.larnaca.setObjectName("larnaca")
        self.verticalLayout.addWidget(self.larnaca)
        self.limassol = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.limassol.setObjectName("limassol")
        self.verticalLayout.addWidget(self.limassol)
        self.minsk = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.minsk.setObjectName("minsk")
        self.verticalLayout.addWidget(self.minsk)
        self.pafos = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pafos.setObjectName("pafos")
        self.verticalLayout.addWidget(self.pafos)
        self.prague = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.prague.setObjectName("prague")
        self.verticalLayout.addWidget(self.prague)
        self.riga = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.riga.setObjectName("riga")
        self.verticalLayout.addWidget(self.riga)
        self.tallin = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tallin.setObjectName("tallin")
        self.verticalLayout.addWidget(self.tallin)
        self.tbilisi = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tbilisi.setObjectName("tbilisi")
        self.verticalLayout.addWidget(self.tbilisi)
        self.torrevieja = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.torrevieja.setObjectName("torrevieja")
        self.verticalLayout.addWidget(self.torrevieja)
        self.narva = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.narva.setObjectName("narva")
        self.verticalLayout.addWidget(self.narva)
        self.bt_ok = QtWidgets.QPushButton(cities)
        self.bt_ok.setGeometry(QtCore.QRect(220, 320, 75, 23))
        self.bt_ok.setObjectName("bt_ok")

        self.retranslateUi(cities)
        QtCore.QMetaObject.connectSlotsByName(cities)

    def retranslateUi(self, cities):
        _translate = QtCore.QCoreApplication.translate
        cities.setWindowTitle(_translate("cities", "Form"))
        self.agianapa.setText(_translate("cities", "Айя-Напа"))
        self.budapesht.setText(_translate("cities", "Будапешт"))
        self.salszburg.setText(_translate("cities", "Зальцбург"))
        self.larnaca.setText(_translate("cities", "Ларнака"))
        self.limassol.setText(_translate("cities", "Лимассол"))
        self.minsk.setText(_translate("cities", "Минск"))
        self.pafos.setText(_translate("cities", "Пафос"))
        self.prague.setText(_translate("cities", "Прага"))
        self.riga.setText(_translate("cities", "Рига"))
        self.tallin.setText(_translate("cities", "Таллин"))
        self.tbilisi.setText(_translate("cities", "Тбилиси"))
        self.torrevieja.setText(_translate("cities", "Торревьеха"))
        self.narva.setText(_translate("cities", "Нарва"))
        self.bt_ok.setText(_translate("cities", "Ok"))
