# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climate.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_climate(object):
    def setupUi(self, climate):
        climate.setObjectName("climate")
        climate.resize(548, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(climate)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 40, 160, 203))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hot = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.hot.setObjectName("hot")
        self.verticalLayout.addWidget(self.hot)
        self.umeren = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.umeren.setObjectName("umeren")
        self.verticalLayout.addWidget(self.umeren)
        self.cold = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cold.setObjectName("cold")
        self.verticalLayout.addWidget(self.cold)
        self.bt_ok = QtWidgets.QPushButton(climate)
        self.bt_ok.setGeometry(QtCore.QRect(220, 290, 75, 23))
        self.bt_ok.setObjectName("bt_ok")

        self.retranslateUi(climate)
        QtCore.QMetaObject.connectSlotsByName(climate)

    def retranslateUi(self, climate):
        _translate = QtCore.QCoreApplication.translate
        climate.setWindowTitle(_translate("climate", "Form"))
        self.hot.setText(_translate("climate", "Жаркий"))
        self.umeren.setText(_translate("climate", "Умеренный"))
        self.cold.setText(_translate("climate", "Холодный"))
        self.bt_ok.setText(_translate("climate", "Ok"))
