# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'countries.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_countries(object):
    def setupUi(self, countries):
        countries.setObjectName("countries")
        countries.resize(548, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(countries)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 10, 160, 295))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.austria = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.austria.setObjectName("austria")
        self.verticalLayout.addWidget(self.austria)
        self.belarussia = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.belarussia.setObjectName("belarussia")
        self.verticalLayout.addWidget(self.belarussia)
        self.hungary = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.hungary.setObjectName("hungary")
        self.verticalLayout.addWidget(self.hungary)
        self.greece = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.greece.setObjectName("greece")
        self.verticalLayout.addWidget(self.greece)
        self.george = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.george.setObjectName("george")
        self.verticalLayout.addWidget(self.george)
        self.spain = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.spain.setObjectName("spain")
        self.verticalLayout.addWidget(self.spain)
        self.cyprus = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cyprus.setObjectName("cyprus")
        self.verticalLayout.addWidget(self.cyprus)
        self.latvia = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.latvia.setObjectName("latvia")
        self.verticalLayout.addWidget(self.latvia)
        self.chezh = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chezh.setObjectName("chezh")
        self.verticalLayout.addWidget(self.chezh)
        self.estonia = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.estonia.setObjectName("estonia")
        self.verticalLayout.addWidget(self.estonia)
        self.bt_ok = QtWidgets.QPushButton(countries)
        self.bt_ok.setGeometry(QtCore.QRect(220, 320, 75, 23))
        self.bt_ok.setObjectName("bt_ok")

        self.retranslateUi(countries)
        QtCore.QMetaObject.connectSlotsByName(countries)

    def retranslateUi(self, countries):
        _translate = QtCore.QCoreApplication.translate
        countries.setWindowTitle(_translate("countries", "Form"))
        self.austria.setText(_translate("countries", "Австрия"))
        self.belarussia.setText(_translate("countries", "Беларусь"))
        self.hungary.setText(_translate("countries", "Венгрия"))
        self.greece.setText(_translate("countries", "Греция"))
        self.george.setText(_translate("countries", "Грузия"))
        self.spain.setText(_translate("countries", "Испания"))
        self.cyprus.setText(_translate("countries", "Кипр"))
        self.latvia.setText(_translate("countries", "Латвия"))
        self.chezh.setText(_translate("countries", "Чехия"))
        self.estonia.setText(_translate("countries", "Эстония"))
        self.bt_ok.setText(_translate("countries", "Ok"))
