# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'currency.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_currency(object):
    def setupUi(self, currency):
        currency.setObjectName("currency")
        currency.resize(548, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(currency)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 40, 160, 203))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.euro = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.euro.setObjectName("euro")
        self.verticalLayout.addWidget(self.euro)
        self.belrub = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.belrub.setObjectName("belrub")
        self.verticalLayout.addWidget(self.belrub)
        self.forint = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.forint.setObjectName("forint")
        self.verticalLayout.addWidget(self.forint)
        self.lari = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.lari.setObjectName("lari")
        self.verticalLayout.addWidget(self.lari)
        self.crona = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.crona.setObjectName("crona")
        self.verticalLayout.addWidget(self.crona)
        self.bt_ok = QtWidgets.QPushButton(currency)
        self.bt_ok.setGeometry(QtCore.QRect(220, 290, 75, 23))
        self.bt_ok.setObjectName("bt_ok")

        self.retranslateUi(currency)
        QtCore.QMetaObject.connectSlotsByName(currency)

    def retranslateUi(self, currency):
        _translate = QtCore.QCoreApplication.translate
        currency.setWindowTitle(_translate("currency", "Form"))
        self.euro.setText(_translate("currency", "Евро"))
        self.belrub.setText(_translate("currency", "Белорусский рубль"))
        self.forint.setText(_translate("currency", "Форинт"))
        self.lari.setText(_translate("currency", "Лари"))
        self.crona.setText(_translate("currency", "Крона"))
        self.bt_ok.setText(_translate("currency", "Ok"))
