# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parking.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_parking(object):
    def setupUi(self, parking):
        parking.setObjectName("parking")
        parking.resize(548, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(parking)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 40, 160, 203))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.yes = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.yes.setObjectName("yes")
        self.verticalLayout.addWidget(self.yes)
        self.no = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.no.setObjectName("no")
        self.verticalLayout.addWidget(self.no)
        self.bt_ok = QtWidgets.QPushButton(parking)
        self.bt_ok.setGeometry(QtCore.QRect(220, 290, 75, 23))
        self.bt_ok.setObjectName("bt_ok")

        self.retranslateUi(parking)
        QtCore.QMetaObject.connectSlotsByName(parking)

    def retranslateUi(self, parking):
        _translate = QtCore.QCoreApplication.translate
        parking.setWindowTitle(_translate("parking", "Form"))
        self.yes.setText(_translate("parking", "Да"))
        self.no.setText(_translate("parking", "Нет"))
        self.bt_ok.setText(_translate("parking", "Ok"))
