# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj_cafe1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cafe(object):
    def setupUi(self, Cafe):
        Cafe.setObjectName("Cafe")
        Cafe.resize(1280, 720)
        self.lb_main = QtWidgets.QLabel(Cafe)
        self.lb_main.setGeometry(QtCore.QRect(100, 50, 211, 41))
        self.lb_main.setStyleSheet("font: 87 22pt \"Segoe UI Black\";")
        self.lb_main.setObjectName("lb_main")
        self.lb_filter = QtWidgets.QLabel(Cafe)
        self.lb_filter.setGeometry(QtCore.QRect(340, 70, 91, 31))
        self.lb_filter.setStyleSheet("font: 75 15pt \"MS Sans Serif\";")
        self.lb_filter.setObjectName("lb_filter")
        self.filter_select = QtWidgets.QComboBox(Cafe)
        self.filter_select.setGeometry(QtCore.QRect(440, 70, 241, 31))
        self.filter_select.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.filter_select.setObjectName("filter_select")
        self.filter_select.addItem("")
        self.setting = QtWidgets.QPushButton(Cafe)
        self.setting.setGeometry(QtCore.QRect(730, 70, 101, 31))
        self.setting.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.setting.setObjectName("setting")
        self.search = QtWidgets.QPushButton(Cafe)
        self.search.setGeometry(QtCore.QRect(910, 70, 101, 31))
        self.search.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.search.setObjectName("search")
        self.lb_sort = QtWidgets.QLabel(Cafe)
        self.lb_sort.setGeometry(QtCore.QRect(340, 140, 131, 31))
        self.lb_sort.setStyleSheet("font: 75 15pt \"MS Sans Serif\";")
        self.lb_sort.setObjectName("lb_sort")
        self.avg_price = QtWidgets.QRadioButton(Cafe)
        self.avg_price.setGeometry(QtCore.QRect(490, 150, 151, 20))
        self.avg_price.setObjectName("avg_price")
        self.my_rate = QtWidgets.QRadioButton(Cafe)
        self.my_rate.setGeometry(QtCore.QRect(670, 150, 71, 21))
        self.my_rate.setObjectName("my_rate")
        self.scrollArea = QtWidgets.QScrollArea(Cafe)
        self.scrollArea.setGeometry(QtCore.QRect(20, 180, 1231, 501))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1212, 499))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Cafe)
        QtCore.QMetaObject.connectSlotsByName(Cafe)

    def retranslateUi(self, Cafe):
        _translate = QtCore.QCoreApplication.translate
        Cafe.setWindowTitle(_translate("Cafe", "Help/Trav - Cafe Search"))
        self.lb_main.setText(_translate("Cafe", "Поиск кафе"))
        self.lb_filter.setText(_translate("Cafe", "Фильтры:"))
        self.filter_select.setItemText(0, _translate("Cafe", "Город"))
        self.setting.setText(_translate("Cafe", "Настроить"))
        self.search.setText(_translate("Cafe", "Поиск"))
        self.lb_sort.setText(_translate("Cafe", "Сортировать:"))
        self.avg_price.setText(_translate("Cafe", "по средней стоимости"))
        self.my_rate.setText(_translate("Cafe", "рейтингу"))
