# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj_city1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_City(object):
    def setupUi(self, City):
        City.setObjectName("City")
        City.resize(1280, 703)
        self.lb_main = QtWidgets.QLabel(City)
        self.lb_main.setGeometry(QtCore.QRect(100, 50, 211, 41))
        self.lb_main.setStyleSheet("font: 87 22pt \"Segoe UI Black\";")
        self.lb_main.setObjectName("lb_main")
        self.lb_filter = QtWidgets.QLabel(City)
        self.lb_filter.setGeometry(QtCore.QRect(340, 100, 91, 31))
        self.lb_filter.setStyleSheet("font: 75 15pt \"MS Sans Serif\";")
        self.lb_filter.setObjectName("lb_filter")
        self.filter_select = QtWidgets.QComboBox(City)
        self.filter_select.setGeometry(QtCore.QRect(440, 100, 241, 31))
        self.filter_select.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.filter_select.setObjectName("filter_select")
        self.filter_select.addItem("")
        self.filter_select.addItem("")
        self.filter_select.addItem("")
        self.setting = QtWidgets.QPushButton(City)
        self.setting.setGeometry(QtCore.QRect(730, 100, 101, 31))
        self.setting.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.setting.setObjectName("setting")
        self.search = QtWidgets.QPushButton(City)
        self.search.setGeometry(QtCore.QRect(910, 100, 101, 31))
        self.search.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.search.setObjectName("search")
        self.lb_sort = QtWidgets.QLabel(City)
        self.lb_sort.setGeometry(QtCore.QRect(340, 170, 131, 31))
        self.lb_sort.setStyleSheet("font: 75 15pt \"MS Sans Serif\";")
        self.lb_sort.setObjectName("lb_sort")
        self.avg_temp = QtWidgets.QRadioButton(City)
        self.avg_temp.setGeometry(QtCore.QRect(490, 177, 151, 20))
        self.avg_temp.setObjectName("avg_temp")
        self.avg_day_cost = QtWidgets.QRadioButton(City)
        self.avg_day_cost.setGeometry(QtCore.QRect(670, 177, 171, 21))
        self.avg_day_cost.setObjectName("avg_day_cost")
        self.scrollArea = QtWidgets.QScrollArea(City)
        self.scrollArea.setGeometry(QtCore.QRect(20, 210, 1241, 451))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1222, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(City)
        QtCore.QMetaObject.connectSlotsByName(City)

    def retranslateUi(self, City):
        _translate = QtCore.QCoreApplication.translate
        City.setWindowTitle(_translate("City", "Help/Trav - City Search"))
        self.lb_main.setText(_translate("City", "Поиск города"))
        self.lb_filter.setText(_translate("City", "Фильтры:"))
        self.filter_select.setItemText(0, _translate("City", "Страна"))
        self.filter_select.setItemText(1, _translate("City", "Климат"))
        self.filter_select.setItemText(2, _translate("City", "Тип отдыха"))
        self.setting.setText(_translate("City", "Настроить"))
        self.search.setText(_translate("City", "Поиск"))
        self.lb_sort.setText(_translate("City", "Сортировать:"))
        self.avg_temp.setText(_translate("City", "по средней температуре"))
        self.avg_day_cost.setText(_translate("City", "средней суточной стоимости"))
