# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj_sights1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sights(object):
    def setupUi(self, Sights):
        Sights.setObjectName("Sights")
        Sights.resize(1280, 720)
        self.lb_main = QtWidgets.QLabel(Sights)
        self.lb_main.setGeometry(QtCore.QRect(100, 40, 491, 41))
        self.lb_main.setStyleSheet("font: 87 22pt \"Segoe UI Black\";")
        self.lb_main.setObjectName("lb_main")
        self.lb_filter = QtWidgets.QLabel(Sights)
        self.lb_filter.setGeometry(QtCore.QRect(340, 100, 91, 31))
        self.lb_filter.setStyleSheet("font: 75 15pt \"MS Sans Serif\";")
        self.lb_filter.setObjectName("lb_filter")
        self.filter_select = QtWidgets.QComboBox(Sights)
        self.filter_select.setGeometry(QtCore.QRect(440, 100, 241, 31))
        self.filter_select.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.filter_select.setObjectName("filter_select")
        self.filter_select.addItem("")
        self.filter_select.addItem("")
        self.setting = QtWidgets.QPushButton(Sights)
        self.setting.setGeometry(QtCore.QRect(730, 100, 101, 31))
        self.setting.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.setting.setObjectName("setting")
        self.search = QtWidgets.QPushButton(Sights)
        self.search.setGeometry(QtCore.QRect(910, 100, 101, 31))
        self.search.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.search.setObjectName("search")
        self.lb_sort = QtWidgets.QLabel(Sights)
        self.lb_sort.setGeometry(QtCore.QRect(340, 170, 131, 31))
        self.lb_sort.setStyleSheet("font: 75 15pt \"MS Sans Serif\";")
        self.lb_sort.setObjectName("lb_sort")
        self.price = QtWidgets.QRadioButton(Sights)
        self.price.setGeometry(QtCore.QRect(490, 177, 151, 20))
        self.price.setObjectName("price")
        self.my_rate = QtWidgets.QRadioButton(Sights)
        self.my_rate.setGeometry(QtCore.QRect(610, 177, 71, 21))
        self.my_rate.setObjectName("my_rate")
        self.scrollArea = QtWidgets.QScrollArea(Sights)
        self.scrollArea.setGeometry(QtCore.QRect(20, 210, 1241, 461))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1222, 459))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Sights)
        QtCore.QMetaObject.connectSlotsByName(Sights)

    def retranslateUi(self, Sights):
        _translate = QtCore.QCoreApplication.translate
        Sights.setWindowTitle(_translate("Sights", "Help/Trav - Sights Search"))
        self.lb_main.setText(_translate("Sights", "Поиск достопримечательностей"))
        self.lb_filter.setText(_translate("Sights", "Фильтры:"))
        self.filter_select.setItemText(0, _translate("Sights", "Город"))
        self.filter_select.setItemText(1, _translate("Sights", "Парковка"))
        self.setting.setText(_translate("Sights", "Настроить"))
        self.search.setText(_translate("Sights", "Поиск"))
        self.lb_sort.setText(_translate("Sights", "Сортировать:"))
        self.price.setText(_translate("Sights", "стоимости"))
        self.my_rate.setText(_translate("Sights", "рейтингу"))
