# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj_country1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Country(object):
    def setupUi(self, Country):
        Country.setObjectName("Country")
        Country.resize(1280, 720)
        self.lb_main = QtWidgets.QLabel(Country)
        self.lb_main.setGeometry(QtCore.QRect(100, 50, 211, 41))
        self.lb_main.setStyleSheet("font: 87 22pt \"Segoe UI Black\";")
        self.lb_main.setObjectName("lb_main")
        self.lb_filter = QtWidgets.QLabel(Country)
        self.lb_filter.setGeometry(QtCore.QRect(340, 100, 91, 31))
        self.lb_filter.setStyleSheet("font: 75 15pt \"MS Sans Serif\";")
        self.lb_filter.setObjectName("lb_filter")
        self.filter_select = QtWidgets.QComboBox(Country)
        self.filter_select.setGeometry(QtCore.QRect(440, 100, 241, 31))
        self.filter_select.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.filter_select.setObjectName("filter_select")
        self.filter_select.addItem("")
        self.filter_select.addItem("")
        self.filter_select.addItem("")
        self.filter_select.addItem("")
        self.setting = QtWidgets.QPushButton(Country)
        self.setting.setGeometry(QtCore.QRect(730, 100, 101, 31))
        self.setting.setStyleSheet("font: 75 12pt \"MS Sans Serif\";")
        self.setting.setObjectName("setting")
        self.search = QtWidgets.QPushButton(Country)
        self.search.setGeometry(QtCore.QRect(910, 100, 101, 31))
        self.search.setStyleSheet("font: 12pt \"MS Sans Serif\";")
        self.search.setObjectName("search")
        self.scrollArea = QtWidgets.QScrollArea(Country)
        self.scrollArea.setGeometry(QtCore.QRect(20, 150, 1231, 511))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1212, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Country)
        QtCore.QMetaObject.connectSlotsByName(Country)

    def retranslateUi(self, Country):
        _translate = QtCore.QCoreApplication.translate
        Country.setWindowTitle(_translate("Country", "Help/Trav - Country Search"))
        self.lb_main.setText(_translate("Country", "Поиск страны"))
        self.lb_filter.setText(_translate("Country", "Фильтры:"))
        self.filter_select.setItemText(0, _translate("Country", "Официальный язык"))
        self.filter_select.setItemText(1, _translate("Country", "Второй язык"))
        self.filter_select.setItemText(2, _translate("Country", "Понимание английского"))
        self.filter_select.setItemText(3, _translate("Country", "Валюта"))
        self.setting.setText(_translate("Country", "Настроить"))
        self.search.setText(_translate("Country", "Поиск"))
