# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rest.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rest(object):
    def setupUi(self, rest):
        rest.setObjectName("rest")
        rest.resize(548, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(rest)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 40, 160, 203))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hot = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.hot.setObjectName("hot")
        self.verticalLayout.addWidget(self.hot)
        self.sight = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.sight.setObjectName("sight")
        self.verticalLayout.addWidget(self.sight)
        self.bt_ok = QtWidgets.QPushButton(rest)
        self.bt_ok.setGeometry(QtCore.QRect(220, 290, 75, 23))
        self.bt_ok.setObjectName("bt_ok")

        self.retranslateUi(rest)
        QtCore.QMetaObject.connectSlotsByName(rest)

    def retranslateUi(self, rest):
        _translate = QtCore.QCoreApplication.translate
        rest.setWindowTitle(_translate("rest", "Form"))
        self.hot.setText(_translate("rest", "Пляжный"))
        self.sight.setText(_translate("rest", "Экскурсионный"))
        self.bt_ok.setText(_translate("rest", "Ok"))
